#!/bin/bash 
# Manual deployment steps from:
# https://github.com/cyberark/sidecar-injector#installing-the-sidecar-injector-manually

source ../config/dap.config
source ./injector.config

TMPDIR=/tmp

if [[ $PLATFORM == openshift ]]; then
  $CLI login -u $CLUSTER_ADMIN_USERNAME
fi

./stp_injector

pushd mgmt_injector
  # create namespace for injectors
  $CLI create namespace $INJECTOR_NAMESPACE_NAME

  ./deployment/webhook-create-signed-cert.sh \
    --service $INJECTOR_LABEL \
    --secret $INJECTOR_LABEL \
    --namespace $INJECTOR_NAMESPACE_NAME

  # Patch the MutatingWebhookConfiguration - set caBundle cluster value
  cat deployment/mutatingwebhook.yaml |    	\
    deployment/webhook-patch-ca-bundle.sh  	\
    --namespace-selector-label $INJECTOR_LABEL	\
    --service $INJECTOR_LABEL			\
    --namespace $INJECTOR_NAMESPACE_NAME		\
    > deployment/mutatingwebhook-ca-bundle.yaml

  $CLI -n $INJECTOR_NAMESPACE_NAME apply -f deployment/deployment.yaml
  $CLI -n $INJECTOR_NAMESPACE_NAME apply -f deployment/service.yaml
  $CLI -n $INJECTOR_NAMESPACE_NAME apply -f deployment/mutatingwebhook-ca-bundle.yaml
  $CLI -n $INJECTOR_NAMESPACE_NAME apply -f deployment/crd.yaml
  $CLI -n $INJECTOR_NAMESPACE_NAME get pods
popd
