#!/bin/bash
set -eou pipefail

source ../config/dap.config

#./0-build-all.sh

main() {
  all_down
  puppet_up
  start_apps
  wait_for_puppet_master
  inject_hf_token
  copy_files_to_puppet_master
}

all_down() {
  echo "-----"
  echo "Bring down all running services"
  docker-compose down
}

puppet_up() {
  echo "-----"
  echo "Bring up Puppet Master"
  docker-compose up -d puppet

  CONJUR_CONT_ID=$CONJUR_MASTER_CONTAINER_NAME
  PUPPET_CONT_ID=$(docker-compose ps -q puppet)

  echo "-----"
  echo "Load demo policy and sample secret value"
  load_policy_REST.sh root ./policy/puppetdemo-policy.yml
  var_value_add_REST.sh puppetdemo/dbpassword 'white rabbit'
  var_value_add_REST.sh puppetdemo/secretkey 'Se(re1Fr0mConjur'

  echo "-----"
  echo "Setup Puppet connection to Conjur service"
  docker cp $MASTER_CERT_FILE $PUPPET_CONT_ID:/etc/conjur.pem
}

start_apps() {
  echo "-----"
  echo "Start demo webapp nodes"
  docker-compose up -d dev-webapp
  docker-compose up -d prod-webapp
}

wait_for_puppet_master() {
  echo
  echo "Waiting 30 secs for Puppet Master initialization..."
  sleep 30
}

inject_hf_token() {
  CONJUR_HF_TOKEN=$(docker exec -it conjur-cli conjur hostfactory tokens create puppetdemo | jq -r .[].token)
  sed -e "s#{{ CONJUR_APPLIANCE_URL }}#https://$CONJUR_MASTER_HOST_NAME:$CONJUR_MASTER_PORT#g" ./puppet/manifests/conjur.pp.template |
	sed -e "s#{{ CONJUR_ACCOUNT }}#$CONJUR_ACCOUNT#g" |
	sed -e "s#{{ CONJUR_HF_TOKEN }}#$CONJUR_HF_TOKEN#g" > ./puppet/manifests/conjur.pp
  echo "HF Token inserted in manifest."
}

copy_files_to_puppet_master() {
  docker cp ./puppet/manifests/ puppet:/etc/puppetlabs/code/environments/production/
  docker cp ./puppet/modules/motd/ puppet:/etc/puppetlabs/code/environments/production/
}

runIncli() {
  docker exec -it $CLI_CONTAINER_NAME "$@"
}

main "$@"
