#!/bin/bash

source ../config/dap.config
source ./vault-sync.config

CLI_CONTAINER_NAME=sync-init-cli

docker run -d \
    --name $CLI_CONTAINER_NAME \
    --label role=cli \
    --restart always \
    --security-opt seccomp:unconfined \
    --add-host "$CONJUR_MASTER_HOST_NAME:$CONJUR_MASTER_HOST_IP" \
    --entrypoint sh \
    $CLI_IMAGE \
    -c "sleep infinity"

# Initialize connection to service (create .conjurrc and conjur-xx.pem cert)
docker exec $CLI_CONTAINER_NAME \
    bash -c "echo yes | conjur init -u $CONJUR_APPLIANCE_URL -a $CONJUR_ACCOUNT"

# Login as admin
docker exec $CLI_CONTAINER_NAME \
    conjur authn login -u admin -p $CONJUR_ADMIN_PASSWORD

sed -e "s#{{ VAULT_NAME }}#$VAULT_NAME#g" \
  ./vault-sync-policy.template |
  sed -e "s#{{ SYNC_HOST }}#$SYNC_HOST#g" \
  > vault-sync-policy.yml
load_policy_REST.sh root vault-sync-policy.yml delete
echo "API key for $SYNC_HOST:" $(docker exec $CLI_CONTAINER_NAME conjur host rotate_api_key -h $SYNC_HOST)

docker stop $CLI_CONTAINER_NAME > /dev/null && docker rm $CLI_CONTAINER_NAME > /dev/null &
