# Define project namespace
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ TEST_APP_NAMESPACE_NAME }}
  labels:
    name: {{ TEST_APP_NAMESPACE_NAME }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secretless-stateful-app
  namespace: {{ TEST_APP_NAMESPACE_NAME }}

# Grant project admin privileges to {{ DEVELOPER_USERNAME }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: project-admin-access-binding
  namespace: {{ TEST_APP_NAMESPACE_NAME }}
subjects:
- kind: User
  name: {{ DEVELOPER_USERNAME }}
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
