---
kind: Service
apiVersion: v1
metadata:
  name: nginx
  namespace: {{ TEST_APP_NAMESPACE_NAME }}
spec:
  selector:
    app: nginx
  ports:
    - port: 8081
      targetPort: 8081

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  serviceName: nginx
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: {{ IMAGE_NAME }}
        imagePullPolicy: {{ IMAGE_PULL_POLICY }}
        ports:
          - containerPort: 8081
