---
kind: Service
apiVersion: v1
metadata:
  name: postgres-db
  namespace: {{ TEST_APP_NAMESPACE_NAME }}
spec:
  selector:
    app: postgres-db
  ports:
    - port: 5432
      targetPort: 5432

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-db
  labels:
    app: postgres-db
spec:
  serviceName: postgres-db
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      serviceAccountName: secretless-stateful-app
      securityContext:
        fsGroup: 999
      containers:
      - name: postgres-db
        imagePullPolicy: {{ IMAGE_PULL_POLICY }}
        image: {{ IMAGE_NAME }}
        ports:
          - containerPort: 5432
        env:
          - name: POSTGRES_USER
            value: test_app
          - name: POSTGRES_PASSWORD
            value: {{ TEST_APP_DB_PASSWORD }}
          - name: POSTGRES_DB
            value: test_app
