---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ SECRETLESS_SERVICEACCOUNT_NAME }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-app-secretless
  name: test-app-secretless
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app-secretless
  template:
    metadata:
      labels:
        app: test-app-secretless
    spec:
      serviceAccountName: {{ SECRETLESS_SERVICEACCOUNT_NAME }}
      containers:
      - image: {{ SECRETLESS_APP_IMAGE }}
        imagePullPolicy: {{ IMAGE_PULL_POLICY }}
        name: test-app-secretless

        env:
          - name: CONN_PG
            value: "host=localhost port=5432 dbname=test_app sslmode=disable"
          - name: CONN_MSSQL
            value: "-U x -P x -Q 'SELECT 1+1' -t 0 -l 0"
          - name: CONN_SSH
            value: "-p 2222 foo@localhost"
          - name: CONN_MYSQL
            value: "-h 127.0.0.1 test_app"
          - name: CONN_HTTP
            value: "http://nginx:8081"
          - name: http_proxy
            value: "http://localhost:8081"

      - image: {{ SECRETLESS_BROKER_IMAGE }}
        imagePullPolicy: {{ IMAGE_PULL_POLICY }}
        name: secretless
        # args refer to values mounted from config map, populated from Conjur
        args: ["-f", "/etc/secretless/secretless.yml"]
        env:

        # values from pod metadata
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP

        # values from DAP config map
          - name: CONJUR_VERSION
            valueFrom:
              configMapKeyRef:
                name: "{{ CONJUR_CONFIG_MAP }}"
                key: CONJUR_VERSION
          - name: CONJUR_ACCOUNT
            valueFrom:
              configMapKeyRef:
                name: "{{ CONJUR_CONFIG_MAP }}"
                key: CONJUR_ACCOUNT
          - name: CONJUR_APPLIANCE_URL
            valueFrom:
              configMapKeyRef:
                name: "{{ CONJUR_CONFIG_MAP }}"
                key: CONJUR_APPLIANCE_URL
          - name: CONJUR_SSL_CERTIFICATE
            valueFrom:
              configMapKeyRef:
                name: "{{ CONJUR_CONFIG_MAP }}"
                key: CONJUR_SSL_CERTIFICATE

        # values from app config map
          - name: CONJUR_AUTHN_URL
            valueFrom:
              configMapKeyRef:
                name: "{{ APP_CONFIG_MAP }}"
                key: conjur-authn-url
          - name: CONJUR_AUTHN_LOGIN
            valueFrom:
              configMapKeyRef:
                name: "{{ APP_CONFIG_MAP }}"
                key: conjur-authn-login

        volumeMounts:
        - name: config
          mountPath: "/etc/secretless"
          readOnly: true
      imagePullSecrets:
        - name: dockerpullsecret
      volumes:
      - name: config
        configMap:
          name: secretless-config
