---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ INJECTED_NAMESPACE_NAME }}
  labels:
    {{ INJECTOR_LABEL }}: enabled
---
apiVersion: v1
kind: Service
metadata:
  name: {{ INJECTED_APP_NAME }}
  labels:
    app: {{ INJECTED_APP_NAME }}
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: {{ INJECTED_APP_NAME }}
  type: LoadBalancer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ INJECTED_SERVICEACCOUNT_NAME }}
  namespace: {{ INJECTED_NAMESPACE_NAME }}
---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    sidecar-injector.cyberark.com/conjurAuthConfig: {{ APP_CONFIG_MAP }}
    sidecar-injector.cyberark.com/conjurConnConfig: {{ CONJUR_CONFIG_MAP }}
    sidecar-injector.cyberark.com/containerMode: {{ INJECTED_CONTAINER_MODE }}
    sidecar-injector.cyberark.com/inject: "yes"
    sidecar-injector.cyberark.com/injectType: {{ INJECTED_CONTAINER_TYPE }}
    sidecar-injector.cyberark.com/containerName: {{ INJECTED_CONTAINER_NAME }}
  labels:
    app: {{ INJECTED_APP_NAME }}
  name: {{ INJECTED_APP_NAME }}
spec:
  serviceAccountName: {{ INJECTED_SERVICEACCOUNT_NAME }}
  containers:
  - image: {{ INJECTED_IMAGE_NAME }}
    imagePullPolicy: {{ IMAGE_PULL_POLICY }}
    name: app
    env:
    # values from DAP config map
      - name: CONJUR_VERSION
        valueFrom:
          configMapKeyRef:
            name: {{ CONJUR_CONFIG_MAP }}
            key: CONJUR_VERSION
      - name: CONJUR_ACCOUNT
        valueFrom:
          configMapKeyRef:
            name: {{ CONJUR_CONFIG_MAP }}
            key: CONJUR_ACCOUNT
      - name: CONJUR_APPLIANCE_URL
        valueFrom:
          configMapKeyRef:
            name: {{ CONJUR_CONFIG_MAP }}
            key: CONJUR_APPLIANCE_URL
      - name: CONJUR_SSL_CERTIFICATE
        valueFrom:
          configMapKeyRef:
            name: {{ CONJUR_CONFIG_MAP }}
            key: CONJUR_SSL_CERTIFICATE
      - name: CONJUR_AUTHN_TOKEN_FILE
        valueFrom:
          configMapKeyRef:
            name: {{ CONJUR_CONFIG_MAP }}
            key: CONJUR_AUTHN_TOKEN_FILE_INJECTED
    volumeMounts:
    - mountPath: /run/conjur
      name: conjur-access-token
