#!/bin/bash
source ./aws.config

sudo docker stop $CONJUR_MASTER_CONTAINER_NAME && \
	sudo docker rm $CONJUR_MASTER_CONTAINER_NAME
sudo docker stop $CLI_CONTAINER_NAME && \
	sudo docker rm $CLI_CONTAINER_NAME
sudo docker stop $CONJUR_FOLLOWER_CONTAINER_NAME && \
	sudo docker rm $CONJUR_FOLLOWER_CONTAINER_NAME
