# Define project namespace
---
apiVersion: v1
kind: Namespace
metadata:
  name: testapps
  labels:
    name: testapps

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secretless-stateful-app
  namespace: testapps

# Grant project admin privileges to baz
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: project-admin-access-binding
  namespace: testapps
subjects:
- kind: User
  name: baz
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
