---
kind: Service
apiVersion: v1
metadata:
  name: mysql-db
  namespace: testapps
spec:
  selector:
    app: mysql-db
  ports:
    - port: 3306
      targetPort: 3306

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-db
  labels:
    app: mysql-db
spec:
  serviceName: mysql-db
  selector:
    matchLabels:
      app: mysql-db
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      serviceAccountName: secretless-stateful-app
      containers:
      - name: mysql-db
        image: 192.168.68.106:5000/mysql:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 3306
        env:
          - name: MYSQL_RANDOM_ROOT_PASSWORD
            value: "yes"
          - name: MYSQL_USER
            value: test_app
          - name: MYSQL_PASSWORD
            value: d0e9cdb51a98d2110aea7850
          - name: MYSQL_DATABASE
            value: test_app
