---
kind: Service
apiVersion: v1
metadata:
  name: nginx
  namespace: testapps
spec:
  selector:
    app: nginx
  ports:
    - port: 8081
      targetPort: 8081

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  serviceName: nginx
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: 192.168.68.106:5000/nginx-secretless:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8081
