---
apiVersion: v1
kind: Service
metadata:
  name: petstore
  labels:
    app: petstore
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: petstore
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: petstore
  name: petstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petstore
  template:
    metadata:
      labels:
        app: petstore
    spec:
      serviceAccountName: secretless-broker
      containers:
      - image: 192.168.68.106:5000/demo-app:latest
        imagePullPolicy: Always
        name: petstore
        ports:
        - name: http
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /pets
            port: http
          initialDelaySeconds: 15
          timeoutSeconds: 5

        env:
          - name: DB_PLATFORM
            value: "mssql"
#            value: "mysql"
#            value: "postgresql"
          - name: DB_URL
            value: "sqlserver://localhost"
#            value: "postgresql://localhost/test_app?sslmode=disable"
          - name: DB_USERNAME
            value: ignore
          - name: DB_PASSWORD
            value: ignore

      - image: 192.168.68.106:5000/secretless-broker:latest
        imagePullPolicy: Always
        name: secretless
        # args refer to values mounted from config map, populated from Conjur
        args: ["-f", "/etc/secretless/secretless.yml"]
        env:

        # values from pod metadata
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP

        # values from DAP config map
          - name: CONJUR_VERSION
            valueFrom:
              configMapKeyRef:
                name: "conjur-config"
                key: CONJUR_VERSION
          - name: CONJUR_ACCOUNT
            valueFrom:
              configMapKeyRef:
                name: "conjur-config"
                key: CONJUR_ACCOUNT
          - name: CONJUR_APPLIANCE_URL
            valueFrom:
              configMapKeyRef:
                name: "conjur-config"
                key: CONJUR_APPLIANCE_URL
          - name: CONJUR_SSL_CERTIFICATE
            valueFrom:
              configMapKeyRef:
                name: "conjur-config"
                key: CONJUR_SSL_CERTIFICATE

        # values from app config map
          - name: CONJUR_AUTHN_URL
            valueFrom:
              configMapKeyRef:
                name: "testapps-config"
                key: conjur-authn-url
          - name: CONJUR_AUTHN_LOGIN
            valueFrom:
              configMapKeyRef:
                name: "testapps-config"
                key: conjur-authn-login

        volumeMounts:
        - name: config
          mountPath: "/etc/secretless"
          readOnly: true
      imagePullSecrets:
        - name: dockerpullsecret
      volumes:
      - name: config
        configMap:
          name: secretless-config
